import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/src/components/ui/provider";
import { LoadingProvider } from "@/src/contexts/loading";
import { Toaster } from "@/src/components/ui/toaster";
import { DialogRoot } from "@/src/components/ui/dialog";

export const metadata: Metadata = {
  title: "Notas",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>
          <LoadingProvider>
            <DialogRoot>
              {children}
            </DialogRoot>
            <Toaster />
          </LoadingProvider>
        </Provider>
      </body>
    </html>
  )
}
