name: Docker Image CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx (used to build images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t lucssdev2005/notas-web:latest .
      
      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push lucssdev2005/notas-web:latest

      # Optionally, tag the image with `latest`
      - name: Tag and push latest image
        run: |
          docker tag lucssdev2005/notas-web:latest lucssdev2005/notas-web:latest
          docker push lucssdev2005/notas-web:latest
